substitutions:
  _GAR_REPOSITORY: "europe-docker.pkg.dev/${PROJECT_ID}/billhop-tools-eu"
  _IMAGE_NAME: "kritis-signer"

options:
  automapSubstitutions: true

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    script: |
      #!/bin/sh -e
      docker build \
        -f ./deploy/kritis-signer/Dockerfile \
        -t "${_GAR_REPOSITORY}/${_IMAGE_NAME}:${COMMIT_SHA}" \
        .

  - name: "gcr.io/cloud-builders/docker"
    id: "publish-image"
    script: |
      #!/bin/sh -e
      docker push "${_GAR_REPOSITORY}/${_IMAGE_NAME}:${COMMIT_SHA}"

      if [ "$BRANCH_NAME" = "billhop-custom" ]; then
        docker tag \
          "${_GAR_REPOSITORY}/${_IMAGE_NAME}:${COMMIT_SHA}" \
          "${_GAR_REPOSITORY}/${_IMAGE_NAME}:latest"
        docker push "${_GAR_REPOSITORY}/${_IMAGE_NAME}:latest"
      fi
